---
- name: Download jenkins-cli from controller
  ansible.builtin.get_url:
    url: '{{ jenkins_cli_jar_uri }}'
    dest: /usr/bin/
    validate_certs: no

- name: Create alias
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: |
      alias jenkins-cli='java \
      -Djavax.net.ssl.trustStore={{ truststore_location }} \
      -Djavax.net.ssl.trustStorePassword={{ truststore_password }} \
      -jar /usr/bin/jenkins-cli.jar \
      -s {{ jenkins_url }}'
    # Find a more secure way to do this

