---
- name: Check os of remote
  set_fact: remote_os="{{ hostvars[inventory_hostname].ansible_distribution }}"

- name: Deploy jenkins master
  import_tasks: deploy_jenkins_master.yml
  when: remote_os == 'Ubuntu'
  failed_when: remote_os != 'Ubuntu'

- name: Install jenkins-cli
  import_tasks: install_jenkins_cli.yml
  when: install_jenkins_cli

- name: Prompt for manual input
  import_tasks: jenkins_setup_wizard.yml

- name: Install additional plugins
  import_tasks: install_plugins.yml
  when: plugins_to_install
