---
- name: Check if Jenkins already installed
  command: apt list --installed jenkins
  register: jenkins_install_check

- name: Parse jenkins_install_check output
  set_fact:
    jenkins_installed: '{{"jenkins/" in jenkins_install_check.stdout }}'

- name: Get Jenkins signature keyring
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
  when: not jenkins_installed

- name: Add jenkins repo to debian-stable repositories # https://www.jenkins.io/doc/book/installing/linux/#debianubuntu
  shell: |
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian-stable binary/ | tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null
  when: not jenkins_installed

- name: Check if correct JAVA already installed
  command: apt list --installed {{ JAVA_VERSION }}
  register: java_install_check

- name: Install Java 11
  apt:
    name: '{{ JAVA_VERSION }}'
    state: present
  when: not '{{ JAVA_VERSION }}' in java_install_check.stdout

- name: Install Jenkins using apt
  apt:
    name: '{{ JENKINS_PACKAGE }}'
    state: present
    update_cache: yes # apt update
    autoremove: yes # Remove unused dependencies

- name: Stop Jenkins
  service:
    name: jenkins
    state: stopped

# HTTPS CONFIG
- name: Deploy HTTPS service config
  block:
    - name: Create keystore and truststore
      import_tasks: create-keystore-and-truststore.yml

    - name: Template Jenkins service file (HTTPS)
      template:
        src:  jenkins.serviceHTTPS.j2
        dest: /lib/systemd/system/jenkins.service
  when: enable_https

# HTTP CONFIG
- name: Template Jenkins service file
  template:
    src:  jenkins.service.j2
    dest: /lib/systemd/system/jenkins.service
  when: not enable_https

- name: reload systemd
  command: systemctl daemon-reload

- name: Start Jenkins
  service:
    name: jenkins
    state: started
